### ISSUE TITLE
add stage3 solution 

### ISSUE THREAD

**Issue by RedJocker** [RedJocker/SimpleBankManagerTestCreation#2]

**Comment by BratinaRok** [comment]
I was thinking, at stage 3 I only added the view Balance screen, what do you think if I also add a transfer funds screen?
Because the view balance screen is not so hard to create and the user could also create a transfer funds screen and create functionality with transfer funds and view balance. What do you think?

**Comment by RedJocker** [comment]
it could have both screens, balance and transfer. I also think the initial balance should be sent the same way as the username and password.
The idea is that on the challenging version this would be fetched through network requests and here we can make this come through the intent instead, with a default value for manual testing reasons.
