### ISSUE TITLE
 Update the description and tests to use consistent currency formatting (either comma or period)

### ISSUE THREAD

**Issue by BratinaRok** [RedJocker/SimpleBankManagerTestCreation#23]

**Comment by RedJocker** [comment]
There are probably a lot of images that you will need to update because of that requirement change and it is important that you reproduce the same flow of use when recreating gifs.

Another thing is that there are other places with money format, like toast messages. Whatever format you choose to keep you have to make sure you keep being consistent with it, you have to update all code that involve money format.

Also you should test the solution you are aiming to give support to which I believe is this:
```
var format = NumberFormat.getCurrencyInstance(Locale("en", "US")).format(balance)
``` 
make sure a implementation with that code can pass, as it is what your modification intend to do

**Comment by RedJocker** [comment]
Description images still need update to sync with the money format change.
For what I could see you need to update all images on stage3 and stage5 and first image on stage4.

**Comment by RedJocker** [comment]
@BratinaRok 
for some reason the resolution of your images are not good when displayed on android studio.
Maybe it is a problem with the software you used to capture the gif. Please remake images without this weird resolution issue.
I use LICEcap when I do the images myself, maybe you can try using it to. Before doing all images confirm if it is displaying properly on android studio
